// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAe5kPyMMJeJ8dPZqIy2vyt95mQzXTQkrM',
    appId: '1:93951643669:web:099dda6fd5037fb9b17e1c',
    messagingSenderId: '93951643669',
    projectId: 'catalift-f6aec',
    authDomain: 'catalift-f6aec.firebaseapp.com',
    storageBucket: 'catalift-f6aec.firebasestorage.app',
    measurementId: 'G-KHZXS44522',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjSKrwxOJN1pTP2cILnXEdXCw7BV9eYtk',
    appId: '1:93951643669:android:0af303ee53e3b655b17e1c',
    messagingSenderId: '93951643669',
    projectId: 'catalift-f6aec',
    storageBucket: 'catalift-f6aec.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAV_vDAK1fO1t5I4rYWu50WUoR_FmYvDEk',
    appId: '1:93951643669:ios:61bea995369c5c84b17e1c',
    messagingSenderId: '93951643669',
    projectId: 'catalift-f6aec',
    storageBucket: 'catalift-f6aec.firebasestorage.app',
    iosBundleId: 'com.example.flutterTaskCatalift',
  );
}
